#Requires -Version 7
<#
.SYNOPSIS
    Publishes the demo UI to the Static Web App.

.DESCRIPTION
    Generates web/config.js from Terraform outputs, then deploys the folder
    with the Static Web Apps CLI via npx, so nothing needs installing globally.

    The deployment token is passed through an environment variable and never
    written to disk. web/config.js IS written to disk and is git-ignored,
    because it carries the APIM subscription key.

    On that subscription key: it ships to the browser, so anyone with the site
    URL can call the API. That is a deliberate, documented compromise for a
    rate-limited environment you tear down between demos (SPEC.md 9.4), and it
    should never be presented as a production pattern.

.EXAMPLE
    ./scripts/deploy-web.ps1
#>
[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$repoRoot = Split-Path -Parent $PSScriptRoot
$infraDir = Join-Path $repoRoot 'infra'
$webDir = Join-Path $repoRoot 'web'

function Get-TerraformOutput {
    param([Parameter(Mandatory)][string]$Name)

    Push-Location $infraDir
    try {
        $value = terraform output -raw $Name 2>$null
        if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($value)) {
            throw "Terraform output '$Name' is unavailable. Run 'terraform apply' in infra/ first."
        }
        return $value.Trim()
    }
    finally {
        Pop-Location
    }
}

foreach ($tool in 'terraform', 'npx', 'az') {
    if (-not (Get-Command $tool -ErrorAction SilentlyContinue)) {
        throw "'$tool' was not found on PATH. See the prerequisites in README.md."
    }
}

Write-Host 'Reading Terraform outputs...' -ForegroundColor Cyan
$gateway = Get-TerraformOutput -Name 'gateway_url'
$subscriptionKey = Get-TerraformOutput -Name 'subscription_key'
$siteName = Get-TerraformOutput -Name 'static_web_app_name'
$siteUrl = Get-TerraformOutput -Name 'static_web_app_url'
$deployToken = Get-TerraformOutput -Name 'static_web_app_api_key'
$resourceGroup = Get-TerraformOutput -Name 'resource_group_name'
$appInsights = Get-TerraformOutput -Name 'application_insights_name'
$subscriptionId = (az account show --query id -o tsv)

$appInsightsUrl = "https://portal.azure.com/#@/resource/subscriptions/$subscriptionId/resourceGroups/$resourceGroup/providers/Microsoft.Insights/components/$appInsights/overview"

Write-Host "  site    : $siteName"
Write-Host "  gateway : $gateway"

# Regenerated on every deploy so a rotated key never goes stale in the page.
$configPath = Join-Path $webDir 'config.js'
$config = @"
// GENERATED by scripts/deploy-web.ps1 - do not edit, do not commit.
// Carries the APIM subscription key, which reaches the browser. See SPEC.md 9.4.
window.DEMO_CONFIG = {
  gatewayUrl: "$gateway",
  subscriptionKey: "$subscriptionKey",
  appInsightsUrl: "$appInsightsUrl"
};
"@

Set-Content -Path $configPath -Value $config -Encoding utf8
Write-Host "  wrote   : web/config.js (git-ignored)"

Write-Host "`nDeploying $webDir ..." -ForegroundColor Cyan

# Token via environment variable rather than an argument, so it stays out of
# the process list and shell history.
$env:SWA_CLI_DEPLOYMENT_TOKEN = $deployToken
try {
    npx --yes @azure/static-web-apps-cli deploy $webDir --env production --no-use-keychain
    if ($LASTEXITCODE -ne 0) {
        throw "static-web-apps-cli deploy failed with exit code $LASTEXITCODE."
    }
}
finally {
    Remove-Item Env:\SWA_CLI_DEPLOYMENT_TOKEN -ErrorAction SilentlyContinue
}

Write-Host "`nDeployed: $siteUrl" -ForegroundColor Green
